_target_: src.smart.model.smart_flow.SMARTFlow
model_config:
  lr: 0.0005
  lr_warmup_steps: 2
  lr_total_steps: ${trainer.max_epochs}
  lr_min_ratio: 0.01
  n_rollout_closed_val: 8
  n_batch_sim_agents_metric: 10
  sim_agents_metric_workers: 4
  n_vis_batch: 0
  n_vis_scenario: 0
  n_vis_rollout: 0
  delete_local_videos_after_wandb_upload: false
  val_open_loop: true
  val_closed_loop: true
  validation_open_seed: 0
  validation_closed_seed: 0
  token_processor:
    map_token_file: "map_traj_token5.pkl"
    agent_token_file: "agent_vocab_555_s2.pkl"
    map_token_sampling:
      num_k: 1
      temp: 1.0
    agent_token_sampling:
      num_k: 1
      temp: 1.0
  validation_rollout_sampling:
    sample_steps: 4
    sample_method: midpoint
    noise_scale: 1.0
  decoder:
    hidden_dim: 128
    num_freq_bands: 64
    num_heads: 8
    head_dim: 15
    dropout: 0.1
    hist_drop_prob: 0.1
    num_map_layers: 2
    num_agent_layers: 6
    pl2pl_radius: 10
    pl2a_radius: 30
    a2a_radius: 60
    time_span: 30
    num_historical_steps: 11
    num_future_steps: 80
    flow_dim: 96
    flow_num_chunk_heads: 4
    flow_num_chunk_layers: 1
    flow_solver_steps: 4
    flow_solver_method: midpoint
    flow_solver_eps: 1.0e-3
  sim_agents_submission:
    is_active: false
    method_name: "SMART-flow-7M"
    authors: [Anonymous]
    affiliation: YOUR_AFFILIATION
    description: YOUR_DESCRIPTION
    method_link: YOUR_METHOD_LINK
    account_name: YOUR_ACCOUNT_NAME
  finetune: false
