# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: ${task_name}
  save_dir: "${paths.output_dir}"
  offline: False
  id: null
  anonymous: null
  project: ${oc.env:WANDB_PROJECT,SMART-FLOW}
  log_model: False
  prefix: ""
  entity: ${oc.env:WANDB_ENTITY,jksg01019-naver-labs}
  group: ""
  tags: []
  job_type: ""
  resume: allow
  settings:
    _target_: wandb.sdk.wandb_settings.Settings
    _disable_stats: True
