wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: ${task_name}
  save_dir: "${paths.output_dir}"
  offline: False
  id: null
  anonymous: null
  project: SMART-FLOW
  log_model: all
  prefix: ""
  entity: jksg01019-naver-labs
  group: ""
  tags: []
  job_type: ""
  resume: allow
  settings:
    _target_: wandb.Settings
    _disable_stats: true
