# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: ${task_name}
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # 같은 실험을 이어서 기록하려면 올바른 id를 넘긴다.
  anonymous: null # 익명 logging을 켜려면 설정한다.
  project: SMART-FLOW
  log_model: all # Lightning checkpoint를 W&B model artifact로 업로드한다.
  prefix: "" # metric key 앞에 붙일 문자열
  entity: jksg01019-naver-labs
  group: ""
  tags: []
  job_type: ""
  resume: allow
