defaults:
  - model_checkpoint
  - epoch_last_checkpoint
  - model_summary
  - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  save_last: link
  auto_insert_metric_name: false

model_summary:
  max_depth: -1

wandb_runtime_metrics:
  _target_: src.utils.wandb_runtime_callback.WandbRuntimeMetricsCallback
  log_every_n_steps: 20
